#!/bin/bash
directory=$1
filename=$2

if [ ! -f "$directory/$filename" ]; then
    echo "File not found."
    python closestmatch.py $directory $filename
else
    echo "$(cat "$directory/$filename")"
fi
